Add sesman-unlink-all-buffer
vspinu/sesman pull request #22
Opened 2021-08-28 05:16 UTC by markgdawson

Add an interactive utility function sesman-unlink-all-buffer to quickly unlinks all sessions linked to this buffer.

2021-08-30 08:20 UTC, vspinu requested changes
`sesman-unlink` offers  [`*all*` option ](https://github.com/vspinu/sesman/blob/90974f9fcf944580de9c3698b5234fa57eddde1e/sesman.el#L301-L302) Why is this not enough?

2021-08-30 08:20 UTC, vspinu commented on sesman.el
> +        (sesman-current-links 'CIDER))
Cider specific

2021-08-30 08:20 UTC, vspinu commented on sesman.el
> +(defun sesman-unlink-all-context ()
Name should probably be just sesman-unlink-all.

2021-08-30 15:05 UTC, markgdawson commented
@vspinu the `*all*` option at the moment can only be used through `completing-read`, which to my mind makes it awkward to bind to keys or to call from elisp snippets.

My use case is to call it non-interactively to force unlink everything so that the next link that I set is sure to be active. 

See here:

https://github.com/markgdawson/polybar-clj.el/blob/4297b91f7d1de68f00ea472d350baba4208869a0/polybar-clj.el#L254

It seemed like a useful function to share. And although I don't use it interactively (yet?),  I can imagine it being useful.

2021-08-30 15:39 UTC, vspinu commented
How about adding `all` argument to `sesman-unlink` instead of a new function? Something like this:

```diff
   (sesman--link-session-interactively session nil nil))
 
 ;;;###autoload
-(defun sesman-unlink ()
-  "Break any of the previously created links."
-  (interactive)
+(defun sesman-unlink (&optional all)
+  "Break any of the previously created links.
+If ALL is non-nil, break all currently existing links."
+  (interactive "P")
   (let* ((system (sesman--system))
          (links (or (sesman-current-links system)
                     (user-error "No %s links found" system))))
     (mapc #'sesman--unlink
-          (sesman--ask-for-link "Unlink: " links 'ask-all)))
+          (if all
+              links
+            (sesman--ask-for-link "Unlink: " links 'ask-all))))
   (run-hooks 'sesman-post-command-hook))
 
 (declare-function sesman-browser "sesman-browser")
```

2021-08-30 16:41 UTC, markgdawson commented
That works for me.

2021-08-30 16:49 UTC, markgdawson commented
If also be happy with passing `links` into the function? Which could be more flexible?

2021-08-30 19:47 UTC, vspinu commented
yep, makes sense indeed.

2021-08-31 05:41 UTC, markgdawson commented
How about something like:
```diff
 ;;;###autoload
-(defun sesman-unlink ()
-  "Break any of the previously created links."
-  (interactive)
-  (let* ((system (sesman--system))
-         (links (or (sesman-current-links system)
-                    (user-error "No %s links found" system))))
-    (mapc #'sesman--unlink
-          (sesman--ask-for-link "Unlink: " links 'ask-all)))
+(defun sesman-unlink (&optional links)
+  "Break any of the previously created links or LINKS if provided."
+  (interactive (list (sesman--ask-for-link "Unlink: "
+                                           (or
+                                            (sesman-current-links (sesman--system))
+                                            (user-error "No %s links found" (sesman--system)))
+                                           'ask-all)))
+  (mapc #'sesman--unlink links)
   (run-hooks 'sesman-post-command-hook))
```

2021-08-31 05:49 UTC, markgdawson commented
Something like:
```clojure
;;;###autoload
(defun sesman-unlink (&optional links)
  "Break any of the previously created links or break LINKS if non-nil."
  (interactive)
  (mapc #'sesman--unlink (or links
                             (sesman--ask-for-link "Unlink: "
                                                   (or
                                                    (sesman-current-links (sesman--system))
                                                    (user-error "No %s links found" (sesman--system)))
                                                   'ask-all)))
  (run-hooks 'sesman-post-command-hook))
```

2021-08-31 05:58 UTC, markgdawson commented
My understanding is that `--` in a name typically denoted something that isn't part of the public interface (whatever that means). So `sesman--system` might suggest it's internal.

Should there be a `sesman-system` (without `--`) function for public consumption? So that something like the following can be used as part of a supported API?
```
(sesman-unlink (sesman-current-links (sesman-system)))
```

Or maybe I'm overthinking this?

2021-08-31 20:25 UTC, vspinu commented on sesman.el
> +(defun sesman-unlink (&optional links)
Can you make it work with C-u  interactively to mean all links?

2021-08-31 20:28 UTC, vspinu commented
> Should there be a sesman-system (without --) 

`sesman-system` is already a variable which can be a function. This is why the `sesman--system`.  Can be named `sesman-get-system` or something, but I think sesman--system is so stable that it's very unlikely to change in the future.

2021-09-01 10:51 UTC, markgdawson commented
Pushed an implementation which uses `current-prefix-args`, so that the behaviour of `(sesman-unlink)` is preserved.

2021-09-01 11:02 UTC, markgdawson commented
> but I think `sesman--system` is so stable that it's very unlikely to change in the future.

This makes a lot of sense. Personally I'm more than happy to just use `sesman--system` in my stuff.

But maybe this is a communication thing? I had assumed that `sesman--system` was internal because of the `--`, and I was looking for something which was public and "safe to use". Other people might jump to the same conclusion?

There could be something like:
```
(defun sesman-get-system ()
  (sesman--system))`
 ```
 
Which could remove the confusion, and at the same time avoid breaking anything which currently uses `sesman--system`.

2021-09-01 11:25 UTC, merged

2021-09-01 11:26 UTC, vspinu commented
Thanks!

Regarding sesman-get-system, it can be an alias. I will add that.